server:
  port: 9527

spring:
  application:
    name: spring-cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
#        这一块后期看下作用
#        - id: activity-route
#          uri: lb://activity
#          predicates:
#            - Path=/activity/**
#          filters:
#            - StripPrefix=1
        - id: spring-cloud-base
          uri: lb://spring-cloud-base
          predicates:
            - Path=/base/**
          filters:
            - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

